# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sepatu_pb2 as sepatu__pb2


class SepatuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/sepatu.SepatuService/List",
            request_serializer=sepatu__pb2.SepatuListRequest.SerializeToString,
            response_deserializer=sepatu__pb2.SepatuListResponse.FromString,
        )
        self.Get = channel.unary_unary(
            "/sepatu.SepatuService/Get",
            request_serializer=sepatu__pb2.SepatuRequest.SerializeToString,
            response_deserializer=sepatu__pb2.SepatuResponse.FromString,
        )
        self.Create = channel.unary_unary(
            "/sepatu.SepatuService/Create",
            request_serializer=sepatu__pb2.SepatuCreateRequest.SerializeToString,
            response_deserializer=sepatu__pb2.SepatuCreateResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/sepatu.SepatuService/Update",
            request_serializer=sepatu__pb2.SepatuUpdateRequest.SerializeToString,
            response_deserializer=sepatu__pb2.SepatuUpdateResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            "/sepatu.SepatuService/Delete",
            request_serializer=sepatu__pb2.SepatuDeleteRequest.SerializeToString,
            response_deserializer=sepatu__pb2.SepatuDeleteResponse.FromString,
        )


class SepatuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SepatuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=sepatu__pb2.SepatuListRequest.FromString,
            response_serializer=sepatu__pb2.SepatuListResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=sepatu__pb2.SepatuRequest.FromString,
            response_serializer=sepatu__pb2.SepatuResponse.SerializeToString,
        ),
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=sepatu__pb2.SepatuCreateRequest.FromString,
            response_serializer=sepatu__pb2.SepatuCreateResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=sepatu__pb2.SepatuUpdateRequest.FromString,
            response_serializer=sepatu__pb2.SepatuUpdateResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=sepatu__pb2.SepatuDeleteRequest.FromString,
            response_serializer=sepatu__pb2.SepatuDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sepatu.SepatuService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SepatuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sepatu.SepatuService/List",
            sepatu__pb2.SepatuListRequest.SerializeToString,
            sepatu__pb2.SepatuListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sepatu.SepatuService/Get",
            sepatu__pb2.SepatuRequest.SerializeToString,
            sepatu__pb2.SepatuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sepatu.SepatuService/Create",
            sepatu__pb2.SepatuCreateRequest.SerializeToString,
            sepatu__pb2.SepatuCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sepatu.SepatuService/Update",
            sepatu__pb2.SepatuUpdateRequest.SerializeToString,
            sepatu__pb2.SepatuUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sepatu.SepatuService/Delete",
            sepatu__pb2.SepatuDeleteRequest.SerializeToString,
            sepatu__pb2.SepatuDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
