# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sepatu.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csepatu.proto\x12\x06sepatu\"h\n\x06Sepatu\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x06 \x01(\t\x12\r\n\x05stock\x18\x07 \x01(\x05\"\x13\n\x11SepatuListRequest\"5\n\x12SepatuListResponse\x12\x1f\n\x07sepatus\x18\x01 \x03(\x0b\x32\x0e.sepatu.Sepatu\"\x1b\n\rSepatuRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x0eSepatuResponse\x12\x1e\n\x06sepatu\x18\x01 \x01(\x0b\x32\x0e.sepatu.Sepatu\"i\n\x13SepatuCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05\"6\n\x14SepatuCreateResponse\x12\x1e\n\x06sepatu\x18\x01 \x01(\x0b\x32\x0e.sepatu.Sepatu\"u\n\x13SepatuUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\"6\n\x14SepatuUpdateResponse\x12\x1e\n\x06sepatu\x18\x01 \x01(\x0b\x32\x0e.sepatu.Sepatu\"!\n\x13SepatuDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x14SepatuDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd3\x02\n\rSepatuService\x12=\n\x04List\x12\x19.sepatu.SepatuListRequest\x1a\x1a.sepatu.SepatuListResponse\x12\x34\n\x03Get\x12\x15.sepatu.SepatuRequest\x1a\x16.sepatu.SepatuResponse\x12\x43\n\x06\x43reate\x12\x1b.sepatu.SepatuCreateRequest\x1a\x1c.sepatu.SepatuCreateResponse\x12\x43\n\x06Update\x12\x1b.sepatu.SepatuUpdateRequest\x1a\x1c.sepatu.SepatuUpdateResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.sepatu.SepatuDeleteRequest\x1a\x1c.sepatu.SepatuDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sepatu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEPATU']._serialized_start=24
  _globals['_SEPATU']._serialized_end=128
  _globals['_SEPATULISTREQUEST']._serialized_start=130
  _globals['_SEPATULISTREQUEST']._serialized_end=149
  _globals['_SEPATULISTRESPONSE']._serialized_start=151
  _globals['_SEPATULISTRESPONSE']._serialized_end=204
  _globals['_SEPATUREQUEST']._serialized_start=206
  _globals['_SEPATUREQUEST']._serialized_end=233
  _globals['_SEPATURESPONSE']._serialized_start=235
  _globals['_SEPATURESPONSE']._serialized_end=283
  _globals['_SEPATUCREATEREQUEST']._serialized_start=285
  _globals['_SEPATUCREATEREQUEST']._serialized_end=390
  _globals['_SEPATUCREATERESPONSE']._serialized_start=392
  _globals['_SEPATUCREATERESPONSE']._serialized_end=446
  _globals['_SEPATUUPDATEREQUEST']._serialized_start=448
  _globals['_SEPATUUPDATEREQUEST']._serialized_end=565
  _globals['_SEPATUUPDATERESPONSE']._serialized_start=567
  _globals['_SEPATUUPDATERESPONSE']._serialized_end=621
  _globals['_SEPATUDELETEREQUEST']._serialized_start=623
  _globals['_SEPATUDELETEREQUEST']._serialized_end=656
  _globals['_SEPATUDELETERESPONSE']._serialized_start=658
  _globals['_SEPATUDELETERESPONSE']._serialized_end=697
  _globals['_SEPATUSERVICE']._serialized_start=700
  _globals['_SEPATUSERVICE']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
